"""fix wrong base for artwork

Revision ID: 6c5747afff20
Revises: 7e3b2fbc8026
Create Date: 2024-10-17 18:57:41.357619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6c5747afff20"
down_revision: Union[str, None] = "7e3b2fbc8026"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artwork", "email")
    op.drop_column("artwork", "username")
    op.drop_column("user", "test_string")
    op.drop_column("user", "test")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("test", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "test_string",
            sa.VARCHAR(),
            server_default=sa.text("'some-string'"),
            nullable=False,
        ),
    )
    op.add_column("artwork", sa.Column("username", sa.VARCHAR(), nullable=False))
    op.add_column("artwork", sa.Column("email", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
