"""rename like table to favorite

Revision ID: 810876afd61d
Revises: 0d7d8634930c
Create Date: 2024-10-26 14:51:17.076325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "810876afd61d"
down_revision: Union[str, None] = "0d7d8634930c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userfavoriteartwork",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("artwork_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artwork.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "artwork_id"),
    )
    op.drop_table("userlikeartwork")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userlikeartwork",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("artwork_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["artwork_id"], ["artwork.id"], name="userlikeartwork_artwork_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="userlikeartwork_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "artwork_id", name="userlikeartwork_pkey"),
    )
    op.drop_table("userfavoriteartwork")
    # ### end Alembic commands ###
