"""artwork_timestamp

Revision ID: e4e56b317030
Revises: 25b34bc28eb6
Create Date: 2024-10-17 16:59:03.164646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'e4e56b317030'
down_revision: Union[str, None] = '25b34bc28eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('artwork', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'updated_at')
    op.drop_column('artwork', 'created_at')
    # ### end Alembic commands ###
