"""user_timestamp

Revision ID: fda898ce048f
Revises: e4e56b317030
Create Date: 2024-10-17 17:00:52.662835

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fda898ce048f"
down_revision: Union[str, None] = "e4e56b317030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
